# Generated by Django 5.1.6 on 2025-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_is_soft_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(default="The CEO", max_length=100),
            preserve_default=False,
        ),
    ]
